import './global.css';
import type {Metadata} from 'next';
import {Lato} from 'next/font/google';
import {ThemeProvider} from '@/components/theme-provider';
import NavBar from '@/components/NavBar';
import {Toaster} from './components/ui/toaster';

import {cn} from '@/lib/utils';

const lato = Lato({
  subsets: ['latin'],
  variable: '--font-sans',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased flex flex-col items-center w-full',
          lato.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
